import json

def create_notebook():
    nb = {
        "cells": [
            {
                "cell_type": "markdown",
                "metadata": {},
                "source": [
                    "# 🎙️ Lumini AI Studio - VoxCPM2 Ultra 48kHz Free GPU Server\n",
                    "### 🚀 100% Free Zero-Shot Studio Voice Cloning Engine (OpenBMB 48kHz)\n",
                    "\n",
                    "---\n",
                    "### 📌 မြန်မာလို အသုံးပြုနည်း လမ်းညွှန်:\n",
                    "1. အပေါ် Menu မှ **Runtime** ➡️ **Change runtime type** ➡️ **T4 GPU** ရွေးထားကြောင်း စစ်ဆေးပါ။\n",
                    "2. အောက်ပါ Cell များကို အပေါ်မှအောက်သို့ **Run (Play button နှိပ်ပါ)**။\n",
                    "3. **Google Drive Mount** ခွင့်ပြုထားပါက Model Weights များကို Drive တွင် အမြဲတမ်း သိမ်းဆည်းထားမည်ဖြစ်သဖြင့် **နောက်တစ်ကြိမ် ပြန် Run လျှင် ဒေါင်းလုဒ် ပြန်စောင့်စရာမလိုဘဲ ၅ စက္ကန့်အတွင်း ချက်ချင်း အဆင်သင့် ဖြစ်ပါမည်!**\n",
                    "4. အောက်ဆုံးတွင် ထွက်လာသော `https://xxxx.trycloudflare.com` URL ကို Lumini Web App (Voiceover Studio) ထဲသို့ ကူးယူထည့်သွင်းပါ။"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ================================================================\n",
                    "# Step 1: GPU စစ်ဆေးခြင်း နှင့် Google Drive Cache (ဒေါင်းလုဒ် မစောင့်ရအောင်)\n",
                    "# ================================================================\n",
                    "import os, sys, subprocess\n",
                    "\n",
                    "# 1. GPU Check\n",
                    "gpu_info = subprocess.getoutput(\"nvidia-smi -L\")\n",
                    "if \"NVIDIA\" not in gpu_info and \"GPU\" not in gpu_info:\n",
                    "    print(\"❌ GPU မတွေ့ရှိပါ။ Runtime -> Change runtime type -> T4 GPU ကို ရွေးချယ်ပြီးမှ ပြန် Run ပါ။\")\n",
                    "    sys.exit(1)\n",
                    "else:\n",
                    "    print(f\"✅ GPU တွေ့ရှိပါသည်: {gpu_info}\")\n",
                    "\n",
                    "# 2. Google Drive Caching (Model ကို Drive တွင် အမြဲသိမ်းဆည်းထားမည်ဖြစ်၍ ထပ်ခါထပ်ခါ ဒေါင်းစရာမလိုတော့ပါ)\n",
                    "USE_DRIVE_CACHE = True # အကြံပြုချက်: True ထားပေးပါ\n",
                    "\n",
                    "cache_dir = \"/content/drive/MyDrive/Lumini_VoxCPM_Cache\"\n",
                    "if USE_DRIVE_CACHE:\n",
                    "    try:\n",
                    "        from google.colab import drive\n",
                    "        print(\"📂 Google Drive ကို ချိတ်ဆက်နေပါသည် (Model cache သိမ်းဆည်းရန်)...\", flush=True)\n",
                    "        drive.mount('/content/drive', force_remount=False)\n",
                    "        os.makedirs(cache_dir, exist_ok=True)\n",
                    "        os.environ[\"HF_HOME\"] = cache_dir\n",
                    "        os.environ[\"TRANSFORMERS_CACHE\"] = cache_dir\n",
                    "        os.environ[\"TORCH_HOME\"] = cache_dir\n",
                    "        print(f\"⚡ Google Drive Cache ဖွင့်လှစ်ပြီးပါပြီ! သိမ်းဆည်းရာနေရာ: {cache_dir}\")\n",
                    "    except Exception as drive_err:\n",
                    "        print(f\"⚠️ Google Drive mount ကျရှုံးပါသည် ({drive_err})။ Default local cache သုံးပါမည်။\")\n",
                    "        os.makedirs(\"/content/model_cache\", exist_ok=True)\n",
                    "        os.environ[\"HF_HOME\"] = \"/content/model_cache\"\n",
                    "else:\n",
                    "    os.makedirs(\"/content/model_cache\", exist_ok=True)\n",
                    "    os.environ[\"HF_HOME\"] = \"/content/model_cache\"\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ================================================================\n",
                    "# Step 2: လိုအပ်သော Packages များနှင့် Cloudflare Tunnel သွင်းယူခြင်း\n",
                    "# ================================================================\n",
                    "print(\"⏳ လိုအပ်သော AI Packages များ ထည့်သွင်းနေပါသည် (~30s)...\", flush=True)\n",
                    "!apt-get update -qq && apt-get install -y -qq ffmpeg ninja-build wget\n",
                    "!pip install -q --upgrade pip\n",
                    "!pip install -q voxcpm ninja fastapi uvicorn soundfile torch torchaudio python-multipart pycloudflared\n",
                    "\n",
                    "# Official cloudflared binary install\n",
                    "if not os.path.exists(\"/usr/local/bin/cloudflared\"):\n",
                    "    !wget -q -nc https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64 -O /usr/local/bin/cloudflared && chmod +x /usr/local/bin/cloudflared\n",
                    "\n",
                    "print(\"✅ Packages အားလုံး ထည့်သွင်းပြီးစီးပါပြီ!\")\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ================================================================\n",
                    "# Step 3: High-Performance FastAPI Speech Server တည်ဆောက်ခြင်း\n",
                    "# ================================================================\n",
                    "server_script = r'''import os\n",
                    "import io\n",
                    "import gc\n",
                    "import sys\n",
                    "import time\n",
                    "import uuid\n",
                    "import tempfile\n",
                    "from pathlib import Path\n",
                    "from typing import Optional\n",
                    "import soundfile as sf\n",
                    "import torch\n",
                    "import numpy as np\n",
                    "import re\n",
                    "from fastapi import FastAPI, UploadFile, File, Form, HTTPException\n",
                    "from fastapi.responses import Response, JSONResponse\n",
                    "from fastapi.middleware.cors import CORSMiddleware\n",
                    "import uvicorn\n",
                    "\n",
                    "app = FastAPI(title=\"Lumini VoxCPM2 Free GPU Engine\", version=\"2.0.0\")\n",
                    "\n",
                    "# Enable Full Cross-Origin Access for Lumini Web App\n",
                    "app.add_middleware(\n",
                    "    CORSMiddleware,\n",
                    "    allow_origins=[\"*\"],\n",
                    "    allow_credentials=True,\n",
                    "    allow_methods=[\"*\"],\n",
                    "    allow_headers=[\"*\"],\n",
                    ")\n",
                    "\n",
                    "VOICE_PROMPTS_DIR = Path(tempfile.gettempdir()) / \"lumini_voxcpm_prompts\"\n",
                    "VOICE_PROMPTS_DIR.mkdir(parents=True, exist_ok=True)\n",
                    "\n",
                    "model = None\n",
                    "model_error = None\n",
                    "sample_rate = 48000\n",
                    "\n",
                    "print(\"⏳ Loading OpenBMB VoxCPM2 Model into GPU...\", flush=True)\n",
                    "try:\n",
                    "    from voxcpm import VoxCPM\n",
                    "    # Load VoxCPM2 onto CUDA\n",
                    "    model = VoxCPM.from_pretrained(\"openbmb/VoxCPM2\", load_denoiser=False)\n",
                    "    if hasattr(model, 'tts_model') and hasattr(model.tts_model, 'sample_rate'):\n",
                    "        sample_rate = model.tts_model.sample_rate\n",
                    "    print(f\"✅ VoxCPM2 Model loaded successfully into GPU! Sample Rate: {sample_rate}Hz\", flush=True)\n",
                    "except Exception as e:\n",
                    "    import traceback\n",
                    "    traceback.print_exc()\n",
                    "    model_error = str(e)\n",
                    "    print(f\"❌ Model load exception: {e}\", flush=True)\n",
                    "\n",
                    "@app.get(\"/\")\n",
                    "@app.get(\"/health\")\n",
                    "@app.get(\"/api/voxcpm/status\")\n",
                    "def get_status():\n",
                    "    cuda_available = torch.cuda.is_available()\n",
                    "    device_name = torch.cuda.get_device_name(0) if cuda_available else \"CPU\"\n",
                    "    vram_used = round(torch.cuda.memory_allocated(0) / 1024**3, 2) if cuda_available else 0\n",
                    "    vram_total = round(torch.cuda.get_device_properties(0).total_memory / 1024**3, 2) if cuda_available else 0\n",
                    "    \n",
                    "    if model is None:\n",
                    "        return {\n",
                    "            \"online\": False,\n",
                    "            \"ok\": False,\n",
                    "            \"error\": model_error or \"VoxCPM2 model is still downloading/initializing\",\n",
                    "            \"cuda\": cuda_available,\n",
                    "            \"device\": device_name\n",
                    "        }\n",
                    "    return {\n",
                    "        \"online\": True,\n",
                    "        \"ok\": True,\n",
                    "        \"engine\": \"VoxCPM2 (OpenBMB 48kHz High-Fidelity)\",\n",
                    "        \"cuda\": cuda_available,\n",
                    "        \"device\": f\"{device_name} ({vram_used}GB / {vram_total}GB)\",\n",
                    "        \"sample_rate\": sample_rate,\n",
                    "        \"supports_zero_shot\": True,\n",
                    "        \"supports_style_prompting\": True\n",
                    "    }\n",
                    "\n",
                    "@app.post(\"/api/voxcpm/clone\")\n",
                    "def register_voice_sample(\n",
                    "    name: str = Form(...),\n",
                    "    instruction: Optional[str] = Form(\"Energetic movie recap narration style\"),\n",
                    "    transcript: Optional[str] = Form(None),\n",
                    "    file: UploadFile = File(...)\n",
                    "):\n",
                    "    voice_id = str(uuid.uuid4())\n",
                    "    ext = Path(file.filename or \"sample.wav\").suffix.lower() or \".wav\"\n",
                    "    target_path = VOICE_PROMPTS_DIR / f\"{voice_id}{ext}\"\n",
                    "    \n",
                    "    content = file.file.read()\n",
                    "    with open(target_path, \"wb\") as f:\n",
                    "        f.write(content)\n",
                    "\n",
                    "    # Convert to 16kHz/48kHz WAV if needed for optimal zero-shot reference\n",
                    "    wav_target = VOICE_PROMPTS_DIR / f\"{voice_id}.wav\"\n",
                    "    if ext != \".wav\":\n",
                    "        try:\n",
                    "            os.system(f\"ffmpeg -y -i '{target_path}' -ar 48000 -ac 1 '{wav_target}' >/dev/null 2>&1\")\n",
                    "        except Exception:\n",
                    "            pass\n",
                    "\n",
                    "    return {\n",
                    "        \"voiceId\": voice_id,\n",
                    "        \"name\": name,\n",
                    "        \"instruction\": instruction,\n",
                    "        \"message\": \"Sample registered successfully! Ready for 48kHz Zero-Shot cloning.\"\n",
                    "    }\n",
                    "\n",
                    "def split_burmese_smart(text: str, max_chunk_len: int = 140) -> list[str]:\n",
                    "    text = re.sub(r'\\s+', ' ', text).strip()\n",
                    "    if not text:\n",
                    "        return []\n",
                    "    # Split by Burmese full stops and punctuation\n",
                    "    raw_sentences = re.split(r'(?<=[။!?\\n])\\s*', text)\n",
                    "    chunks = []\n",
                    "    current = \"\"\n",
                    "    for s in raw_sentences:\n",
                    "        s = s.strip()\n",
                    "        if not s:\n",
                    "            continue\n",
                    "        if len(current) + len(s) + 1 <= max_chunk_len:\n",
                    "            current = (current + \" \" + s).strip() if current else s\n",
                    "        else:\n",
                    "            if current:\n",
                    "                chunks.append(current)\n",
                    "            if len(s) > max_chunk_len:\n",
                    "                parts = re.split(r'(?<=[၊,])\\s*', s)\n",
                    "                sub_curr = \"\"\n",
                    "                for sp in parts:\n",
                    "                    sp = sp.strip()\n",
                    "                    if not sp:\n",
                    "                        continue\n",
                    "                    if len(sub_curr) + len(sp) + 1 <= max_chunk_len:\n",
                    "                        sub_curr = (sub_curr + \" \" + sp).strip() if sub_curr else sp\n",
                    "                    else:\n",
                    "                        if sub_curr:\n",
                    "                            chunks.append(sub_curr)\n",
                    "                        while len(sp) > max_chunk_len:\n",
                    "                            chunks.append(sp[:max_chunk_len])\n",
                    "                            sp = sp[max_chunk_len:]\n",
                    "                        sub_curr = sp\n",
                    "                current = sub_curr\n",
                    "            else:\n",
                    "                current = s\n",
                    "    if current:\n",
                    "        chunks.append(current)\n",
                    "    return chunks if chunks else [text]\n",
                    "\n",
                    "@app.post(\"/api/voxcpm/synthesize\")\n",
                    "def synthesize_speech(\n",
                    "    voice_id: Optional[str] = Form(None),\n",
                    "    text: str = Form(...),\n",
                    "    instruction: Optional[str] = Form(None),\n",
                    "    speed: float = Form(1.0)\n",
                    "):\n",
                    "    if model is None:\n",
                    "        raise HTTPException(status_code=503, detail=f\"VoxCPM model not ready: {model_error or 'Initializing'}\")\n",
                    "    if not text.strip():\n",
                    "        raise HTTPException(status_code=400, detail=\"Text cannot be empty\")\n",
                    "\n",
                    "    audio_path = None\n",
                    "    if voice_id and voice_id != 'default':\n",
                    "        for ext in [\".wav\", \".mp3\", \".webm\", \".m4a\", \".ogg\"]:\n",
                    "            candidate = VOICE_PROMPTS_DIR / f\"{voice_id}{ext}\"\n",
                    "            if candidate.exists():\n",
                    "                audio_path = str(candidate)\n",
                    "                break\n",
                    "\n",
                    "    chunks = split_burmese_smart(text, max_chunk_len=140)\n",
                    "    print(f\"🎙️ Synthesizing {len(chunks)} chunks...\", flush=True)\n",
                    "\n",
                    "    audio_pieces = []\n",
                    "    pause_samples = int(sample_rate * 0.08)\n",
                    "    pause_array = np.zeros(pause_samples, dtype=np.float32)\n",
                    "\n",
                    "    try:\n",
                    "        for idx, chunk in enumerate(chunks):\n",
                    "            if not chunk.strip():\n",
                    "                continue\n",
                    "            try:\n",
                    "                if audio_path and os.path.exists(audio_path):\n",
                    "                    wav_chunk = model.generate(\n",
                    "                        text=chunk,\n",
                    "                        reference_wav_path=audio_path,\n",
                    "                        cfg_value=2.0,\n",
                    "                        inference_timesteps=10\n",
                    "                    )\n",
                    "                else:\n",
                    "                    wav_chunk = model.generate(\n",
                    "                        text=chunk,\n",
                    "                        cfg_value=2.0,\n",
                    "                        inference_timesteps=10\n",
                    "                    )\n",
                    "                \n",
                    "                if isinstance(wav_chunk, tuple):\n",
                    "                    wav_chunk = wav_chunk[0]\n",
                    "                if hasattr(wav_chunk, 'cpu'):\n",
                    "                    wav_chunk = wav_chunk.cpu().numpy()\n",
                    "                if isinstance(wav_chunk, np.ndarray):\n",
                    "                    wav_chunk = wav_chunk.flatten().astype(np.float32)\n",
                    "                    audio_pieces.append(wav_chunk)\n",
                    "                    audio_pieces.append(pause_array)\n",
                    "            except Exception as chunk_err:\n",
                    "                print(f\"⚠️ Error on chunk {idx}: {chunk_err}\", flush=True)\n",
                    "                continue\n",
                    "\n",
                    "        if not audio_pieces:\n",
                    "            raise HTTPException(status_code=500, detail=\"Failed to generate any audio chunks.\")\n",
                    "\n",
                    "        full_audio = np.concatenate(audio_pieces)\n",
                    "        # Normalize audio\n",
                    "        max_amp = np.max(np.abs(full_audio))\n",
                    "        if max_amp > 1e-5:\n",
                    "            full_audio = full_audio / max_amp * 0.95\n",
                    "\n",
                    "        out_io = io.BytesIO()\n",
                    "        sf.write(out_io, full_audio, sample_rate, format='WAV', subtype='PCM_16')\n",
                    "        out_io.seek(0)\n",
                    "        return Response(content=out_io.read(), media_type=\"audio/wav\")\n",
                    "    finally:\n",
                    "        # Crucial: GPU VRAM Cleanup after each synthesis to prevent OOM crash\n",
                    "        if torch.cuda.is_available():\n",
                    "            torch.cuda.empty_cache()\n",
                    "        gc.collect()\n",
                    "\n",
                    "if __name__ == '__main__':\n",
                    "    uvicorn.run(app, host='0.0.0.0', port=8000, log_level='info')\n",
                    "'''\n",
                    "\n",
                    "with open('app.py', 'w', encoding='utf-8') as f:\n",
                    "    f.write(server_script)\n",
                    "\n",
                    "print(\"✅ FastAPI Engine script written successfully!\")\n"
                ]
            },
            {
                "cell_type": "code",
                "execution_count": None,
                "metadata": {},
                "outputs": [],
                "source": [
                    "# ================================================================\n",
                    "# Step 4: Server Run ခြင်းနှင့် Cloudflare Tunnel ချိတ်ဆက်ခြင်း\n",
                    "# ================================================================\n",
                    "import os, subprocess, time, re, urllib.request, json\n",
                    "\n",
                    "# Clean previous runs\n",
                    "!killall -9 cloudflared python 2>/dev/null; fuser -k 8000/tcp 2>/dev/null; rm -f /tmp/tunnel.log /tmp/app.log\n",
                    "time.sleep(2)\n",
                    "\n",
                    "# 1. Start FastAPI server in background with log capture\n",
                    "app_log = open('/tmp/app.log', 'w')\n",
                    "proc_app = subprocess.Popen(['python', '-u', 'app.py'], stdout=app_log, stderr=app_log)\n",
                    "\n",
                    "# 2. Start Cloudflare Tunnel (Session Timeout မရှိ၊ လုံးဝ ပြုတ်မကျပါ)\n",
                    "tunnel_log = open('/tmp/tunnel.log', 'w')\n",
                    "proc_tunnel = subprocess.Popen(['cloudflared', 'tunnel', '--url', 'http://127.0.0.1:8000'], stdout=tunnel_log, stderr=tunnel_log)\n",
                    "\n",
                    "# 3. Extract Cloudflare URL\n",
                    "fresh_url = None\n",
                    "print(\"⏳ Cloudflare Secure Tunnel ချိတ်ဆက်နေပါသည်...\", flush=True)\n",
                    "for _ in range(30):\n",
                    "    time.sleep(1)\n",
                    "    if os.path.exists('/tmp/tunnel.log'):\n",
                    "        with open('/tmp/tunnel.log', 'r') as f:\n",
                    "            matches = re.findall(r'https://[a-zA-Z0-9-]+\\.trycloudflare\\.com', f.read())\n",
                    "            if matches:\n",
                    "                fresh_url = matches[-1]\n",
                    "                break\n",
                    "\n",
                    "# 4. Healthcheck: Wait until VoxCPM2 is 100% ready in GPU memory\n",
                    "print(\"⏳ Model Weights ကို GPU ပေါ် တင်နေပါသည် (Google Drive Cache ရှိလျှင် ၅ စက္ကန့်သာ ကြာပါမည်)...\", flush=True)\n",
                    "is_ready = False\n",
                    "for attempt in range(120):\n",
                    "    if proc_app.poll() is not None:\n",
                    "        print(f\"❌ Server ရပ်တန့်သွားပါသည် (Exit code: {proc_app.returncode})! Log:\")\n",
                    "        with open('/tmp/app.log') as f:\n",
                    "            print(f.read())\n",
                    "        break\n",
                    "    try:\n",
                    "        req = urllib.request.urlopen(\"http://127.0.0.1:8000/api/voxcpm/status\", timeout=2)\n",
                    "        if req.status == 200:\n",
                    "            data = json.loads(req.read().decode('utf-8'))\n",
                    "            if data.get('online'):\n",
                    "                is_ready = True\n",
                    "                device_info = data.get('device', 'GPU')\n",
                    "                break\n",
                    "    except Exception:\n",
                    "        pass\n",
                    "    time.sleep(1)\n",
                    "\n",
                    "if is_ready and fresh_url:\n",
                    "    print(\"\\n\" + \"=\"*72)\n",
                    "    print(\"🎉 🟢 VOXCPM2 48KHz FREE GPU SERVER IS 100% ONLINE & READY!\")\n",
                    "    print(f\"⚡ Device: {device_info}\")\n",
                    "    print(\"=\"*72)\n",
                    "    print(f\"👉 အောက်ပါ URL ကို Copy ယူပြီး Lumini (Voiceover Studio) ထဲတွင် Paste လုပ်ပါ:\\n\")\n",
                    "    print(f\"      {fresh_url}\\n\")\n",
                    "    print(\"=\"*72 + \"\\n\")\n",
                    "    print(\"💡 စက်မပိတ်ဘဲ ဆက်လက်လည်ပတ်နေစေရန် Keep-Alive စတင်ပါသည်...\")\n",
                    "    try:\n",
                    "        while True:\n",
                    "            time.sleep(30)\n",
                    "            # Print heartbeat and VRAM status every 5 minutes\n",
                    "            if int(time.time()) % 300 < 30:\n",
                    "                print(f\"🟢 [Heartbeat {time.strftime('%H:%M:%S')}] Server is healthy & running!\")\n",
                    "    except KeyboardInterrupt:\n",
                    "        print(\"🛑 Server stopped by user.\")\n",
                    "else:\n",
                    "    print(\"⚠️ Server Initialization Failed. Checking logs:\")\n",
                    "    if os.path.exists('/tmp/app.log'):\n",
                    "        with open('/tmp/app.log') as f:\n",
                    "            print(f.read())\n"
                ]
            }
        ],
        "metadata": {
            "accelerator": "GPU",
            "colab": {
                "gpuType": "T4",
                "provenance": []
            },
            "language_info": {
                "name": "python"
            }
        },
        "nbformat": 4,
        "nbformat_minor": 0
    }

    with open('server/VoxCPM_Colab_Free_GPU.ipynb', 'w', encoding='utf-8') as f:
        json.dump(nb, f, indent=1, ensure_ascii=False)
    print("Successfully wrote server/VoxCPM_Colab_Free_GPU.ipynb")

if __name__ == '__main__':
    create_notebook()
